export function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[–—’'"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function getInsightBySlug(slug) {
  return insightsData.find((item) => slugify(item.title) === slug) || null;
}

export const insightsData = [
  {
    id: 1,
    image: '/insights/3.jpeg',
    title: 'Panel on Responsible AI',
    description: 'Panelist at the Responsible AI conference at Dhirubhai Ambani University – School of Law, alongside leaders from NVIDIA and JSA Advocates.',
    location: 'Gandhinagar, Gujarat',
  },
  {
    id: 2,
    image: '/insights/4.jpeg',
    title: 'AI Competency Framework',
    description: 'Presenting the AI Competency Framework for Government Officials — categorization across Central & State Ministries.',
    location: 'Punjab',
  },
  {
    id: 3,
    image: '/insights/5.jpeg',
    title: 'AI in Administrative Efficiency',
    description: 'Leading a session on AI in Administrative Efficiency for officials at Punjab\u2019s Department of Technical Education & Industrial Training.',
    location: 'Punjab',
  },
  {
    id: 4,
    image: '/insights/8.jpeg',
    title: 'AI Foundation Training — UPSC',
    description: 'A two-day AI Foundation Training for newly recruited Deputy Architects of the UPSC Central Architectural Service.',
    location: 'New Delhi',
  },
  {
    id: 5,
    image: '/insights/9.jpeg',
    title: 'Digital Twin & AI Strategy',
    description: 'AI Foundation Training for Deputy Architects of the UPSC Central Architectural Service — AI strategy, auditing, and Digital Twin simulations.',
    location: 'New Delhi',
  },
  {
    id: 6,
    image: '/insights/11.jpeg',
    title: 'Data Governance & Responsible AI',
    description: 'Delivering a session on Data Governance and Responsible AI for officers of UPSDM as part of an AI Literacy Workshop.',
    location: 'Lucknow, Uttar Pradesh',
  },
  {
    id: 7,
    image: '/insights/12.jpeg',
    title: 'Applied AI for Public Sector',
    description: 'A two-day workshop on Applied & Functional AI for Public Sector at UPSDM — strengthening future-ready AI capabilities in governance.',
    location: 'Lucknow, Uttar Pradesh',
  },
  {
    id: 8,
    image: '/insights/13.jpeg',
    title: 'Sessions at National Law University',
    description: 'Delivering AI-focused sessions at National Law University, Delhi — exploring the intersection of technology, law, and data governance.',
    location: 'New Delhi',
  },
  {
    id: 9,
    image: '/insights/14.jpeg',
    title: 'AI & Research Ethics — JNU',
    description: 'Speaking at Jawaharlal Nehru University on \u201CArtificial Intelligence and Research Ethics\u201D — integrating AI responsibly while preserving academic integrity.',
    location: 'New Delhi',
  },
  {
    id: 10,
    image: '/insights/15.jpeg',
    title: 'India AI Impact Summit 2026',
    description: 'Interacting with young innovators from Sainik School Sujanpur Tira at the India AI Impact Summit 2026 — showcasing impactful AI solutions.',
    location: 'New Delhi',
    focus: 'center 38%',
  },
  {
    id: 11,
    image: '/insights/16.jpeg',
    title: 'Meeting Dr. Rumman Chowdhury',
    description: 'At the India AI Impact Summit 2026 — gaining valuable insights into the evolving challenges of AI governance, policy, and democratic systems.',
    location: 'New Delhi',
    focus: 'center 30%',
  },
  {
    id: 12,
    image: '/insights/17.jpeg',
    title: 'Faculty Development — DYPU Law',
    description: 'A Faculty Development Workshop at DYPU School of Law — ethical AI use, academic workflows, and practical AI tools for teaching and administration.',
    location: 'Pune, Maharashtra',
  },
  {
    id: 13,
    image: '/insights/18.jpeg',
    title: 'Training for CPWD Engineers',
    description: 'Founder & CEO Parishrut Jassal led a specialized training program for CPWD Engineers and Architects on AI in construction and infrastructure.',
    location: 'New Delhi',
  },
  {
    id: 14,
    image: '/insights/19.jpeg',
    title: 'Panelist at AAAI 2026',
    description: 'Panelist at AAAI 2026 in Singapore — contributing to discussions on AI governance, autonomous systems, and human-centered frameworks.',
    location: 'Singapore',
  },
  {
    id: 15,
    image: '/insights/20.jpeg',
    title: 'Partnership — DY Patil University',
    description: 'A new partnership between GovernAI and DY Patil University to advance Responsible AI by bridging technology and law.',
    location: 'Pune, Maharashtra',
  },
  {
    id: 16,
    image: '/insights/21.jpeg',
    title: 'AI & Law Centre — MoU Signing',
    description: 'Signing an MoU with DY Patil University School of Law to establish a dedicated AI & Law Centre advancing responsible AI through research and policy.',
    location: 'Pune, Maharashtra',
  },
  {
    id: 17,
    image: '/insights/22.jpeg',
    title: 'Masterclass at DY Patil University',
    description: 'A masterclass at DY Patil University School of Law during the India AI Impact Summit 2026 pre-summit event on responsible AI practices.',
    location: 'Pune, Maharashtra',
  },
  {
    id: 18,
    image: '/insights/23.jpeg',
    title: 'DPDP & Responsible AI — AIIMS Patna',
    description: 'Chief Compliance Officer Alvin Antony led a session at AIIMS Patna on the DPDP Act 2023, DPDP Rules 2025, and responsible AI in healthcare.',
    location: 'Patna, Bihar',
  },
  {
    id: 19,
    image: '/insights/24.jpeg',
    title: 'IndiaAI Impact Summit — Expert Panel',
    description: 'Joining the expert panel at the IndiaAI Impact Summit 2026 Pre-Summit Event — discussing AI safety, governance, and secure frameworks.',
    location: 'New Delhi',
  },
  {
    id: 20,
    image: '/insights/25.jpeg',
    title: 'AI Governance — Himachal Pradesh',
    description: 'Founder & CEO Parishrut Jassal delivered a session on AI Governance for the Government of Himachal Pradesh, strengthening public sector readiness.',
    location: 'Shimla, Himachal Pradesh',
  },
  {
    id: 21,
    image: '/insights/26.jpeg',
    title: 'TEDxGNLU Talk',
    description: 'Speaking at TEDxGNLU — \u201CThe Matrix Algorithm: From NPCs to Future Architects\u201D — preserving human agency and critical thinking in the age of AI.',
    location: 'Gandhinagar, Gujarat',
  },
  {
    id: 22,
    image: '/insights/27.jpeg',
    title: 'AI & Philanthropy — Asia-Pacific',
    description: 'At the Asia-Pacific Meeting on Artificial Intelligence and Philanthropy — discussions on ethical AI, inclusive innovation, and social impact.',
    location: 'New Delhi',
  },
  {
    id: 23,
    image: '/insights/28.jpeg',
    title: 'AI Horizon Summit',
    description: 'Participating in the AI Horizon Summit, an official pre-summit event for the India AI Impact Summit 2026 — shaping future-ready AI governance pathways.',
    location: 'New Delhi',
  },
  {
    id: 24,
    image: '/insights/29.jpeg',
    title: 'Data Governance — CDAC Mohali',
    description: 'Chief Compliance Officer Alvin Antony delivered a session at the IndiaAI Data Lab, CDAC Mohali on Data Governance, DPDP, and Responsible AI.',
    location: 'Mohali, Punjab',
  },
  {
    id: 25,
    image: '/insights/30.jpeg',
    title: 'SMART Public Service Delivery — IIPA',
    description: 'Speaking at the Three-day Training Program on SMART Public Service Delivery in Urban Planning and Governance at IIPA.',
    location: 'New Delhi',
  },
  {
    id: 26,
    image: '/insights/31.jpeg',
    title: 'Building AI Capacity for Governance',
    description: 'Launching the 10-week \u201CBuilding AI Capacity for Governance\u201D programme at MS-HIPA — strengthening responsible AI within the public sector.',
    location: 'Shimla, Himachal Pradesh',
  },
  {
    id: 27,
    image: '/insights/32.jpeg',
    title: 'Yashoda AI — Chandigarh University',
    description: 'Leading a Yashoda AI session at Chandigarh University on AI literacy, safety, and the responsible use of AI for future technology professionals.',
    location: 'Chandigarh',
  },
  {
    id: 28,
    image: '/insights/33.jpeg',
    title: 'Session at SIRD&PR',
    description: 'Founder & CEO Parishrut Jassal led a session at SIRD&PR, Government of Himachal Pradesh — advancing AI literacy across public sector departments.',
    location: 'Himachal Pradesh',
  },
  {
    id: 29,
    image: '/insights/34.jpeg',
    title: 'AI Literacy at MGSIPA',
    description: 'Conducting a session at MGSIPA, Chandigarh for government officials on AI literacy, responsible AI integration, and public administration.',
    location: 'Chandigarh',
  },
  {
    id: 30,
    image: '/insights/35.jpeg',
    title: 'AI Policy at JSIA, JGU',
    description: 'Delivering a session at the Jindal School of International Affairs (JSIA), JGU on AI policy, governance, and the evolving global AI landscape.',
    location: 'Sonipat, Haryana',
  },
  {
    id: 31,
    image: '/insights/36.jpeg',
    title: 'Empowering Young Minds',
    description: 'Interacting with students at a Government Senior Secondary School in Himachal Pradesh on the responsible use of AI as a tool for learning.',
    location: 'Himachal Pradesh',
  },
  {
    id: 32,
    image: '/insights/37.jpeg',
    title: 'AI in Healthcare — The AI Collective',
    description: 'AI & Healthcare Lead Dr. Mrudula Bhalke spoke at The AI Collective Delhi – Healthcare Chapter on Generative AI, ethics, and responsible innovation.',
    location: 'New Delhi',
  },
  {
    id: 33,
    image: '/insights/38.jpeg',
    title: 'Grassroots Digital Governance',
    description: 'Engaging with government officials and computer operators in Himachal Pradesh on data governance, DPDP principles, and responsible AI practices.',
    location: 'Himachal Pradesh',
  },
  {
    id: 34,
    image: '/insights/39.jpeg',
    title: 'AI Workshops with AILF',
    description: 'Leading AI workshops in Tamil Nadu with the Artificial Intelligence Legislators\u2019 Forum (AILF) on practical AI literacy and responsible adoption.',
    location: 'Tamil Nadu',
  },
  {
    id: 35,
    image: '/insights/40.jpeg',
    title: 'Responsible AI Workshop — IIPA',
    description: 'Associated with IIPA on e-Governance initiatives — conducting a workshop on the responsible use of AI, emphasizing efficiency and human oversight.',
    location: 'New Delhi',
  },
  {
    id: 36,
    image: '/insights/41.jpeg',
    title: 'AI & Healthcare Conference',
    description: 'Speaking at the AI and Healthcare Conference in Mohali on Responsible AI in the public healthcare sector and human-centered healthcare systems.',
    location: 'Mohali, Punjab',
  },
  {
    id: 37,
    image: '/insights/42.jpeg',
    title: 'Digital Health Workshop',
    description: 'AI & Healthcare Lead Dr. Mrudula Bhalke conducted a Digital Health workshop for medical professionals on the ethical, responsible adoption of AI.',
    location: 'India',
  },
  {
    id: 38,
    image: '/insights/43.jpeg',
    title: 'Introduction to AI — MGSIPA',
    description: 'A session for Government of Punjab officials at MGSIPA on AI literacy, responsible AI adoption, and building future-ready public sector capabilities.',
    location: 'Chandigarh',
  },
  {
    id: 39,
    image: '/insights/44.jpeg',
    title: 'HP Working Group Appointment',
    description: 'Appointed as a Member of the Working Group under the Government of Himachal Pradesh — contributing to the vision of Samridh Himachal 2045.',
    location: 'Himachal Pradesh',
  },
  {
    id: 40,
    image: '/insights/45.jpeg',
    title: 'AI Capacity for IAS Officers',
    description: 'A session on \u201CBuilding AI Capacity for Governance\u201D for IAS Probationary Officers and HP Administrative Services officers at MS-HIPA.',
    location: 'Shimla, Himachal Pradesh',
  },
  {
    id: 41,
    image: '/insights/46.jpeg',
    title: 'Public Sector AI Readiness',
    description: 'Delivering a session on \u201CBuilding AI Capacity for Governance\u201D at MS-HIPA — focusing on AI readiness and public sector competencies.',
    location: 'Shimla, Himachal Pradesh',
  },
];
