/*
  Central SEO configuration — single source of truth for site-wide metadata,
  canonical URLs, and structured-data (JSON-LD) building blocks.
  Update SITE_URL here if the production domain changes.
*/

export const SITE_URL = 'https://www.governai.info';

export const SITE = {
  name: 'GovernAI',
  legalName: 'GovernAI OPC Pvt. Ltd.',
  shortName: 'GovernAI',
  url: SITE_URL,
  description:
    'GovernAI delivers AI governance capacity building, ISO/IEC 42001 compliance auditing & responsible AI policy advisory. 2,000+ officials trained across India.',
  // Logo for JSON-LD schemas. OG share image is generated by opengraph-image.js at 1200x630.
  ogImage: '/assets/img/logo.png',
  email: 'contact@governai.info',
  locale: 'en_IN',
  twitter: '@governaiofc',
  foundingYear: '2024',
  address: {
    city: 'New Delhi',
    region: 'Delhi',
    country: 'India',
    countryCode: 'IN',
  },
  sameAs: [
    'https://www.linkedin.com/company/governaiofficial/',
    'https://x.com/governaiofc',
  ],
  developerUrl: 'https://divyakush2006.github.io/divyakush-resume/',
};

/*
  Primary keyword universe — expanded with long-tail, question-based,
  and LSI keywords for maximum niche coverage across all AI governance
  search intents (informational, transactional, navigational).
*/
export const SITE_KEYWORDS = [
  // Core brand + primary
  'AI Governance',
  'AI Governance India',
  'Responsible AI',
  'AI Compliance',
  'GovernAI',

  // Standards & frameworks
  'ISO 42001',
  'ISO/IEC 42001 implementation',
  'ISO 42001 certification India',
  'how to implement ISO 42001',
  'AI auditing',
  'AI audit services India',
  'EU AI Act compliance',
  'NIST AI Risk Management Framework',
  'NIST AI RMF implementation',
  'DPDP Act compliance',
  'DPDP Act compliance services',

  // Services
  'AI policy advisory',
  'AI policy advisory India',
  'AI governance consulting',
  'AI compliance consulting firms',
  'AI governance company India',
  'AI capacity building',
  'AI governance training',
  'AI ethics training for government officials',
  'AI governance capacity building India',
  'responsible AI training programs',

  // Sector-specific
  'public sector AI',
  'government AI training',
  'AI in public administration',
  'AI governance for universities',
  'AI governance for healthcare',

  // Concepts
  'ethical AI frameworks',
  'AI risk management',
  'trustworthy AI',
  'AI bias mitigation',
  'AI safety governance',
  'AI accountability framework',

  // Question-based (People Also Ask targeting)
  'what is AI governance',
  'what is responsible AI',
  'AI governance framework for government',
  'how to ensure AI compliance',
  'AI governance best practices',

  // High-value additions — outrank competitors
  'AI governance platform India',
  'AI governance for public sector',
  'AI compliance India',
  'algorithmic auditing',
  'sovereign AI governance',
  'AI procurement standards',
  'AI literacy government',
  'AI governance consulting India',
  'digital governance AI',
  'AI governance workshop',
  'AI capacity building for government',
  'responsible AI India',
  'DPDP Act 2023',
  'AI governance training for IAS officers',
  'AI governance training for government',
  'AI risk assessment services',
  'AI policy framework India',
  'UKAS ISO 42001',
  'AI governance company',
  // State-specific long-tail keywords
  'AI governance Himachal Pradesh',
  'AI governance Delhi',
  'AI governance Punjab',
  'AI governance Chandigarh',
  'AI governance Bihar',
  'AI governance Gujarat',
  'AI governance Maharashtra',
  'AI governance Karnataka',
  'AI governance Telangana',
  'AI governance Tamil Nadu',
  'AI governance Rajasthan',
  'AI governance Haryana',
  'AI governance Uttar Pradesh',
  'AI governance West Bengal',
  'AI governance Jharkhand',
  'AI training for government officials Delhi',
  'AI training for IAS officers Shimla',
  'AI compliance consulting Bengaluru',
  'AI policy advisory Hyderabad',
  'responsible AI training IIPA Delhi',
  'AI governance MGSIPA Chandigarh',
  'DPDP Act training AIIMS Patna',
  'AI governance workshop Gujarat',
  'ISO 42001 compliance India',
  'AI governance consulting Delhi NCR',
  'AI capacity building Himachal Pradesh',
  'AI governance training Maharashtra',
  'responsible AI workshop Kolkata',
];

/* Reusable Organization JSON-LD (Knowledge Graph eligibility). */
export function organizationSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: SITE.name,
    legalName: SITE.legalName,
    url: SITE_URL,
    logo: {
      '@type': 'ImageObject',
      url: `${SITE_URL}${SITE.ogImage}`,
      width: 512,
      height: 512,
    },
    image: `${SITE_URL}${SITE.ogImage}`,
    description:
      'GovernAI is an AI governance company helping governments, universities, and enterprises deploy AI responsibly. Services span capacity building, ISO/IEC 42001 compliance auditing, and AI policy advisory, with 2,000+ officials trained across 5+ states and 20+ institutional engagements.',
    email: SITE.email,
    foundingDate: SITE.foundingYear,
    foundingLocation: {
      '@type': 'Place',
      address: {
        '@type': 'PostalAddress',
        addressLocality: SITE.address.city,
        addressRegion: SITE.address.region,
        addressCountry: SITE.address.countryCode,
      },
    },
    knowsLanguage: ['English', 'Hindi'],
    address: {
      '@type': 'PostalAddress',
      addressLocality: SITE.address.city,
      addressRegion: SITE.address.region,
      addressCountry: SITE.address.countryCode,
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: '28.6139',
      longitude: '77.2090',
    },
    areaServed: [
      { '@type': 'Country', name: 'India' },
      { '@type': 'AdministrativeArea', name: 'Himachal Pradesh, India' },
      { '@type': 'AdministrativeArea', name: 'Chandigarh, India' },
      { '@type': 'AdministrativeArea', name: 'Punjab, India' },
      { '@type': 'AdministrativeArea', name: 'Haryana, India' },
      { '@type': 'AdministrativeArea', name: 'Delhi, India' },
      { '@type': 'AdministrativeArea', name: 'Rajasthan, India' },
      { '@type': 'AdministrativeArea', name: 'Uttar Pradesh, India' },
      { '@type': 'AdministrativeArea', name: 'Bihar, India' },
      { '@type': 'AdministrativeArea', name: 'Jharkhand, India' },
      { '@type': 'AdministrativeArea', name: 'West Bengal, India' },
      { '@type': 'AdministrativeArea', name: 'Gujarat, India' },
      { '@type': 'AdministrativeArea', name: 'Maharashtra, India' },
      { '@type': 'AdministrativeArea', name: 'Karnataka, India' },
      { '@type': 'AdministrativeArea', name: 'Telangana, India' },
      { '@type': 'AdministrativeArea', name: 'Tamil Nadu, India' },
      { '@type': 'Country', name: 'Singapore' },
    ],
    knowsAbout: [
      'AI Governance',
      'Responsible AI',
      'AI Compliance',
      'ISO/IEC 42001',
      'AI Auditing',
      'AI Policy',
      'AI Risk Management',
      'AI Ethics',
      'NIST AI RMF',
      'EU AI Act',
      'DPDP Act',
    ],
    founder: { '@id': `${SITE_URL}/#founder` },
    employee: [
      { '@id': `${SITE_URL}/#founder` },
      { '@id': `${SITE_URL}/#person-alvin-antony` },
      { '@id': `${SITE_URL}/#person-utso-guha-roy` },
      { '@id': `${SITE_URL}/#person-anubhav-sharma` },
      { '@id': `${SITE_URL}/#person-himanshu-kalia` },
      { '@id': `${SITE_URL}/#person-preekshit-singh` },
    ],
    sameAs: SITE.sameAs,
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'customer support',
      email: SITE.email,
      areaServed: ['IN', 'US', 'GB', 'SG'],
      availableLanguage: ['English', 'Hindi'],
    },
    numberOfEmployees: {
      '@type': 'QuantitativeValue',
      minValue: 5,
      maxValue: 15,
    },
    slogan: 'Governing Artificial Intelligence for a Responsible Future',
  };
}

/* WebSite JSON-LD (enables sitelinks search box eligibility + entity linking). */
export function websiteSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_URL}/#website`,
    url: SITE_URL,
    name: SITE.name,
    alternateName: 'GovernAI India',
    description:
      'Governing Artificial Intelligence for a responsible future — capacity building, compliance, and policy advisory.',
    publisher: { '@id': `${SITE_URL}/#organization` },
    inLanguage: 'en-IN',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${SITE_URL}/?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

/* ProfessionalService JSON-LD — strongest fit for a B2B advisory/consultancy. */
export function professionalServiceSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${SITE_URL}/#service`,
    name: SITE.name,
    image: `${SITE_URL}${SITE.ogImage}`,
    url: SITE_URL,
    email: SITE.email,
    priceRange: '$$',
    address: {
      '@type': 'PostalAddress',
      addressLocality: SITE.address.city,
      addressRegion: SITE.address.region,
      addressCountry: SITE.address.countryCode,
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: '28.6139',
      longitude: '77.2090',
    },
    areaServed: [
      { '@type': 'Country', name: 'India' },
      { '@type': 'AdministrativeArea', name: 'Himachal Pradesh, India' },
      { '@type': 'AdministrativeArea', name: 'Chandigarh, India' },
      { '@type': 'AdministrativeArea', name: 'Punjab, India' },
      { '@type': 'AdministrativeArea', name: 'Haryana, India' },
      { '@type': 'AdministrativeArea', name: 'Delhi, India' },
      { '@type': 'AdministrativeArea', name: 'Rajasthan, India' },
      { '@type': 'AdministrativeArea', name: 'Uttar Pradesh, India' },
      { '@type': 'AdministrativeArea', name: 'Bihar, India' },
      { '@type': 'AdministrativeArea', name: 'Jharkhand, India' },
      { '@type': 'AdministrativeArea', name: 'West Bengal, India' },
      { '@type': 'AdministrativeArea', name: 'Gujarat, India' },
      { '@type': 'AdministrativeArea', name: 'Maharashtra, India' },
      { '@type': 'AdministrativeArea', name: 'Karnataka, India' },
      { '@type': 'AdministrativeArea', name: 'Telangana, India' },
      { '@type': 'AdministrativeArea', name: 'Tamil Nadu, India' },
      { '@type': 'Country', name: 'Singapore' },
    ],
    parentOrganization: { '@id': `${SITE_URL}/#organization` },
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'AI Governance Services',
      itemListElement: [
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: 'GovernAI Academy — Capacity Building & Training',
            description:
              'Executive sensitisation, immersive workshops, hands-on GenAI tooling, and NSQF-aligned academic courses for government officials, university faculty, and enterprise teams.',
            serviceType: 'AI Governance Training',
          },
        },
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: 'AI Compliance — Auditing & Regulatory Assurance',
            description:
              'Compliance gap analysis, ISO/IEC 42001 readiness, independent AI auditing, and conformity assessments aligned with global standards including EU AI Act and NIST AI RMF.',
            serviceType: 'AI Compliance Auditing',
          },
        },
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: 'AI Policy Advisory',
            description:
              'Strategic AI policy formulation, regulatory readiness assessments, and DPDP Act compliance advisory for public and private sector organizations.',
            serviceType: 'AI Policy Consulting',
          },
        },
      ],
    },
  };
}

/* BreadcrumbList helper for sub-pages. */
export function breadcrumbSchema(items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: `${SITE_URL}${it.path}`,
    })),
  };
}

/* ItemList schema for insights — enables rich carousel in Google results. */
export function insightsItemListSchema(insights, slugify) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'GovernAI Insights — AI Governance Knowledge',
    description:
      'Expert insights, event recaps, and thought leadership on AI governance, responsible AI, and compliance from GovernAI.',
    numberOfItems: insights.length,
    itemListElement: insights.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      url: `${SITE_URL}/insights/${slugify(item.title)}/`,
      name: item.title,
    })),
  };
}

/* ─────────────────────────  PEOPLE  ───────────────────────── */

/* Founder — Person schema (links to the Organization as founder/employee). */
export function founderSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE_URL}/#founder`,
    name: 'Parishrut Jassal',
    givenName: 'Parishrut',
    familyName: 'Jassal',
    jobTitle: 'Founder & Chief Executive Officer',
    worksFor: { '@id': `${SITE_URL}/#organization` },
    founder: { '@id': `${SITE_URL}/#organization` },
    image: `${SITE_URL}/assets/img/founder/founder.jpg`,
    url: SITE_URL,
    nationality: { '@type': 'Country', name: 'India' },
    description:
      'TEDx Speaker and UKAS-recognised ISO/IEC 42001 Auditor. Working Group Member (Digital & AI Governance) on I.T. Infrastructure, Cyber-Hubs & Future Ready Industries for the Government of Himachal Pradesh, former Deputy Advisor at NIEPA (Ministry of Education), Doctoral Researcher on the Global Governance of AI for Sustainable Peace, and member of ForHumanity (USA) on AI Audits & Regulation.',
    knowsAbout: [
      'AI Governance',
      'Responsible AI',
      'ISO/IEC 42001',
      'AI Policy',
      'AI Auditing',
      'AI Safety',
    ],
    knowsLanguage: ['English', 'Hindi'],
    memberOf: [{ '@type': 'Organization', name: 'ForHumanity' }],
    hasCredential: [
      {
        '@type': 'EducationalOccupationalCredential',
        credentialCategory: 'certification',
        name: 'UKAS-recognised ISO/IEC 42001 Lead Auditor',
      },
    ],
    award: 'TEDx Speaker',
    sameAs: ['https://linkedin.com/in/parishrut-jassal'],
  };
}

/* Key team members — lightweight Person nodes tied to the Organization. */
export function teamSchema() {
  const people = [
    {
      id: 'alvin-antony',
      name: 'Alvin Antony',
      jobTitle: 'Chief Compliance Officer',
      image: '/assets/img/Team/team_alvin.jpeg',
      description:
        'AI & Frontier Tech Lawyer specialising in AI Governance, ISO 42001, IP and Data Protection. Certified Implementer/Auditor in ISO 42001:2023 and ISO 9001:2015.',
      knowsAbout: ['AI Compliance', 'ISO/IEC 42001', 'Data Protection', 'AI Law'],
    },
    {
      id: 'utso-guha-roy',
      name: 'Dr. Utso Guha Roy',
      jobTitle: 'AI & Healthcare Lead',
      image: '/assets/img/Team/team_utso.png',
      description:
        'MD in Pathology (2018), Certified in AI Medicine (CCAIM), with Post-Doctoral work in Digital Pathology.',
      knowsAbout: ['AI in Healthcare', 'Digital Pathology', 'Responsible AI'],
    },
    {
      id: 'anubhav-sharma',
      name: 'Anubhav Sharma',
      jobTitle: 'Technical & Security Lead',
      image: '/assets/img/Team/team_anubhav.jpeg',
      description:
        'Information security architect specializing in security methodologies, compliance frameworks, risk assessment, and audit engagements. Leads technical infrastructure and cybersecurity initiatives.',
      knowsAbout: ['DevSecOps', 'Cloud Security', 'Cybersecurity'],
    },
    {
      id: 'himanshu-kalia',
      name: 'Dr. Himanshu Kalia',
      jobTitle: 'AI & Healthcare Consultant',
      image: '/assets/img/Team/team_himanshu.jpeg',
      description:
        'Scientific Officer at IIT DRISHTI CPS with an MSc from the University of Glasgow. Contributes expertise in healthcare research, scientific innovation, and AI applications.',
      knowsAbout: ['AI in Healthcare', 'Healthcare Research', 'Interdisciplinary Technology'],
    },
    {
      id: 'preekshit-singh',
      name: 'Er. Preekshit Singh',
      jobTitle: 'Operations & Training Lead',
      image: '/assets/img/Team/team_preekshit.png',
      description:
        'Civil engineer overseeing academy operations, training delivery, process optimization, and organizational execution across initiatives.',
      knowsAbout: ['Operations Management', 'Training Delivery', 'Process Optimization'],
    },
  ];

  return people.map((p) => ({
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE_URL}/#person-${p.id}`,
    name: p.name,
    jobTitle: p.jobTitle,
    worksFor: { '@id': `${SITE_URL}/#organization` },
    image: `${SITE_URL}${p.image}`,
    description: p.description,
    knowsAbout: p.knowsAbout,
  }));
}

/* Chief Advisor — Person schema. */
export function advisorSchema() {
  return [
    {
      '@context': 'https://schema.org',
      '@type': 'Person',
      '@id': `${SITE_URL}/#advisor-murthy-remilla`,
      name: 'Dr. Murthy Remilla',
      jobTitle: 'President, Telemedicine Society of India',
      worksFor: { '@id': `${SITE_URL}/#organization` },
      image: `${SITE_URL}/assets/img/team_murthy.png`,
      description:
        'Former ISRO Scientist and leader in healthcare technology and digital transformation. Advises on AI governance, healthcare innovation, and telemedicine adoption.',
      alumniOf: { '@type': 'Organization', name: 'ISRO' },
      knowsAbout: ['AI Governance', 'Healthcare Technology', 'Telemedicine'],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Person',
      '@id': `${SITE_URL}/#advisor-maya-sherman`,
      name: 'Maya Sherman',
      jobTitle: 'International AI Policy Advisor',
      worksFor: { '@id': `${SITE_URL}/#organization` },
      image: `${SITE_URL}/assets/img/team_maya.jpeg`,
      description:
        'Former Science, Technology, and Innovation Attaché at the Embassy of Israel. Provides strategic guidance on AI governance, international policy frameworks, and responsible AI development.',
      knowsAbout: ['AI Policy', 'International Governance', 'Responsible AI'],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Person',
      '@id': `${SITE_URL}/#advisor-arun-pandit`,
      name: 'Arun Pandit',
      jobTitle: 'Industry Advisor',
      worksFor: { '@id': `${SITE_URL}/#organization` },
      image: `${SITE_URL}/assets/img/team_arun.png`,
      description:
        'Co-Founder of Hyphen SCS, Chairman of AIMA Young Leaders Council, and TEDx Speaker. Brings experience in entrepreneurship, leadership development, and business strategy.',
      knowsAbout: ['Entrepreneurship', 'Leadership Development', 'Business Strategy'],
    },
  ];
}

/* Website developer — Person schema for Divyakush Punjabi. Accepts
   dynamic data from getDeveloperData() for build-time freshness.
   Enhanced with mainEntityOfPage, makesOffer, hasCredential for
   Knowledge Panel eligibility. */
export function developerSchema(data) {
  const d = data || {};
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE_URL}/#developer-divyakush-punjabi`,
    name: d.name || 'Divyakush Punjabi',
    givenName: 'Divyakush',
    familyName: 'Punjabi',
    jobTitle: d.jobTitle || 'Full Stack Developer & AI Engineer',
    description:
      d.bio ||
      'Full Stack Developer and AI Engineer specializing in enterprise web applications, AI/ML integration, and UI/UX engineering.',
    url: SITE.developerUrl,
    mainEntityOfPage: 'https://divyakush2006.github.io/divyakush-resume/',
    ...(d.avatar ? { image: d.avatar } : {}),
    sameAs: [
      SITE.developerUrl,
      d.github || 'https://github.com/divyakush2006',
      d.linkedin || 'https://linkedin.com/in/divyakush-punjabi',
      ...(d.blog ? [d.blog] : []),
    ],
    knowsAbout: [
      'Web Development',
      'Next.js',
      'React',
      'TypeScript',
      'UI/UX Design',
      'Front-end Engineering',
      'AI/ML Integration',
      'Full Stack Development',
      'Responsive Design',
      'Performance Optimization',
    ],
    makesOffer: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Full Stack Web Development',
          description: 'Enterprise web application development using Next.js, React, and modern frameworks.',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI/ML Integration',
          description: 'Integration of artificial intelligence and machine learning capabilities into web applications.',
        },
      },
    ],
    hasCredential: [
      {
        '@type': 'EducationalOccupationalCredential',
        credentialCategory: 'degree',
        educationalLevel: 'Bachelor',
        recognizedBy: { '@type': 'CollegeOrUniversity', name: 'Vellore Institute of Technology' },
      },
    ],
    ...(d.location ? { homeLocation: { '@type': 'Place', name: d.location } } : {}),
    ...(d.company ? { worksFor: { '@type': 'Organization', name: d.company } } : {}),
    alumniOf: [
      { '@type': 'CollegeOrUniversity', name: 'Vellore Institute of Technology' },
      { '@type': 'CollegeOrUniversity', name: 'Indian Institute of Technology, Ropar' },
    ],
    nationality: { '@type': 'Country', name: 'India' },
    email: 'divyakushpunjabi@gmail.com',
  };
}

/* Article schema for insight/blog pages. */
export function articleSchema({ slug, title, description, image, location, datePublished, author }) {
  const wordCount = description ? description.split(/\s+/).length : 0;
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    '@id': `${SITE_URL}/insights/${slug}/#article`,
    headline: title,
    description: description,
    image: {
      '@type': 'ImageObject',
      url: `${SITE_URL}${image}`,
      caption: title,
    },
    datePublished: datePublished || undefined,
    dateModified: datePublished || undefined,
    author: author
      ? { '@type': 'Person', name: author }
      : { '@id': `${SITE_URL}/#organization` },
    publisher: { '@id': `${SITE_URL}/#organization` },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${SITE_URL}/insights/${slug}/` },
    wordCount,
    inLanguage: 'en-IN',
    ...(location
      ? { contentLocation: { '@type': 'Place', name: location } }
      : {}),
  };
}

/* Event schema — insights that are conferences, workshops, or summits
   become eligible for Google Event rich results (date, location cards).
   Auto-inferred: any insight with a location and datePublished is treated
   as an event. */
export function eventSchema({ slug, title, description, image, location, datePublished, author }) {
  if (!location || !datePublished) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationEvent',
    '@id': `${SITE_URL}/insights/${slug}/#event`,
    name: title,
    description: description,
    startDate: datePublished,
    endDate: datePublished,
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    location: {
      '@type': 'Place',
      name: location,
      address: {
        '@type': 'PostalAddress',
        addressLocality: location,
        addressCountry: 'IN',
      },
    },
    image: image ? `${SITE_URL}${image}` : undefined,
    organizer: {
      '@type': 'Organization',
      '@id': `${SITE_URL}/#organization`,
      name: 'GovernAI',
      url: SITE_URL,
    },
    performer: author
      ? { '@type': 'Person', name: author }
      : { '@id': `${SITE_URL}/#organization` },
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'INR',
      availability: 'https://schema.org/InStock',
      url: `${SITE_URL}/insights/${slug}/`,
    },
    inLanguage: 'en-IN',
  };
}

/* ─────────────────────────  CONTENT SCHEMAS  ───────────────────────── */

/* WebPage schema for the home page — with SpeakableSpecification for voice search. */
export function webPageSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': `${SITE_URL}/#webpage`,
    url: SITE_URL,
    name: 'GovernAI — AI Governance, Compliance & ISO 42001',
    description:
      'GovernAI delivers AI governance capacity building, ISO/IEC 42001 compliance auditing & responsible AI policy advisory. 2,000+ officials trained across 10+ states in India.',
    isPartOf: { '@id': `${SITE_URL}/#website` },
    about: { '@id': `${SITE_URL}/#organization` },
    inLanguage: 'en-IN',
    primaryImageOfPage: { '@type': 'ImageObject', url: `${SITE_URL}${SITE.ogImage}` },
    speakable: {
      '@type': 'SpeakableSpecification',
      cssSelector: ['h1', '.ds-lead', '.ds-card-desc'],
    },
    lastReviewed: new Date().toISOString().split('T')[0],
    breadcrumb: {
      '@type': 'BreadcrumbList',
      itemListElement: [
        {
          '@type': 'ListItem',
          position: 1,
          name: 'Home',
          item: SITE_URL,
        },
      ],
    },
  };
}

/* FAQ schema — eligible for "People Also Ask" rich results. */
export const FAQS = [
  {
    q: 'What does GovernAI do?',
    a: 'GovernAI provides the architectural framework to deploy, monitor, and scale AI systems with absolute compliance and zero bias. We specialise in AI governance capacity building, ISO/IEC 42001 compliance auditing, and AI policy advisory for governments, universities, and enterprises.',
  },
  {
    q: 'What is AI governance?',
    a: 'AI governance is the set of policies, frameworks, and oversight mechanisms that ensure artificial intelligence systems are deployed responsibly — meeting regulatory standards, mitigating bias, and aligning with ethical and legal requirements such as ISO/IEC 42001, the EU AI Act, and the NIST AI Risk Management Framework.',
  },
  {
    q: 'Does GovernAI help with ISO/IEC 42001 compliance?',
    a: 'Yes. GovernAI offers compliance gap analysis, pre-assessment and readiness reviews, independent AI auditing, and conformity assessments aligned with ISO/IEC 42001 — the international standard for AI Management Systems.',
  },
  {
    q: 'Who does GovernAI work with?',
    a: 'GovernAI partners with government bodies, universities, research institutions, and enterprises. We have trained 2000+ officials across 5+ states and engaged 20+ institutions across India.',
  },
  {
    q: 'How can I contact GovernAI?',
    a: 'You can reach the GovernAI team via the contact form on our website or by email at contact@governai.info. We respond within one business day.',
  },
];

export function faqSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    '@id': `${SITE_URL}/#faq`,
    mainEntity: FAQS.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };
}

/* CreativeWork schema — declares GovernAI website as a WebApplication
   built by Divyakush Punjabi. Google uses this to build entity
   associations ("Divyakush Punjabi built GovernAI"). */
export function creativeWorkSchema(dev) {
  const d = dev || {};
  return {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    '@id': `${SITE_URL}/#web-application`,
    name: 'GovernAI',
    url: SITE_URL,
    description: SITE.description,
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web',
    creator: {
      '@type': 'Person',
      '@id': `${SITE_URL}/#developer-divyakush-punjabi`,
      name: d.name || 'Divyakush Punjabi',
      url: 'https://divyakush2006.github.io/divyakush-resume/',
    },
    sourceOrganization: {
      '@type': 'Organization',
      '@id': `${SITE_URL}/#organization`,
      name: 'GovernAI',
    },
    dateCreated: '2025-01-01',
    inLanguage: 'en-IN',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'INR',
      availability: 'https://schema.org/InStock',
    },
  };
}

/* ── State-specific service area schemas ──
   Generates an ItemList of GovernAI's engagements across Indian states.
   Each entry links to the state, institutions, and service types delivered.
   This signals verified geographic presence to Google for local ranking. */
export function stateServiceAreasSchema() {
  const STATE_ENGAGEMENTS = [
    {
      state: 'Himachal Pradesh', stateCode: 'HP',
      institutions: [
        { name: 'MS-HIPA, Shimla', type: 'GovernmentOrganization', service: 'AI Governance Capacity Building' },
        { name: 'SIRD&PR, Himachal Pradesh', type: 'GovernmentOrganization', service: 'AI Governance Training' },
        { name: 'Government of Himachal Pradesh — AI Working Group', type: 'GovernmentOrganization', service: 'AI Policy Advisory' },
      ],
    },
    {
      state: 'Chandigarh', stateCode: 'CH',
      institutions: [
        { name: 'MGSIPA, Chandigarh', type: 'GovernmentOrganization', service: 'AI Literacy & Governance Training' },
        { name: 'Chandigarh University', type: 'EducationalOrganization', service: 'AI Governance Academic Program' },
      ],
    },
    {
      state: 'Punjab', stateCode: 'PB',
      institutions: [
        { name: 'Dept. of Technical Education & Training, Punjab', type: 'GovernmentOrganization', service: 'AI Governance Training' },
        { name: 'C-DAC Mohali', type: 'GovernmentOrganization', service: 'Data Governance & Responsible AI' },
        { name: 'MGSIPA', type: 'GovernmentOrganization', service: 'AI Introduction for Government Officers' },
      ],
    },
    {
      state: 'Haryana', stateCode: 'HR',
      institutions: [
        { name: 'OP Jindal Global University', type: 'EducationalOrganization', service: 'AI Policy & Governance Session' },
      ],
    },
    {
      state: 'Delhi', stateCode: 'DL',
      institutions: [
        { name: 'Indian Institute of Public Administration (IIPA)', type: 'GovernmentOrganization', service: 'Responsible AI Workshop for Senior Officials' },
        { name: 'NIEPA, Ministry of Education', type: 'GovernmentOrganization', service: 'AI in Administrative Efficiency' },
        { name: 'National Law University, Delhi', type: 'EducationalOrganization', service: 'AI Governance & Law Sessions' },
        { name: 'Jawaharlal Nehru University (JNU)', type: 'EducationalOrganization', service: 'AI Research Ethics' },
        { name: 'National CPWD Academy', type: 'GovernmentOrganization', service: 'AI for Public Service Delivery' },
      ],
    },
    {
      state: 'Rajasthan', stateCode: 'RJ',
      institutions: [
        { name: 'ICFAI Jaipur', type: 'EducationalOrganization', service: 'AI Governance Panel Discussion' },
        { name: 'National Law University, Jodhpur', type: 'EducationalOrganization', service: 'AI & Law Session' },
      ],
    },
    {
      state: 'Uttar Pradesh', stateCode: 'UP',
      institutions: [
        { name: 'UP Skill Development Mission', type: 'GovernmentOrganization', service: 'AI Capacity Building' },
      ],
    },
    {
      state: 'Bihar', stateCode: 'BR',
      institutions: [
        { name: 'AIIMS Patna', type: 'MedicalOrganization', service: 'DPDP Act & Responsible AI in Healthcare' },
      ],
    },
    {
      state: 'Jharkhand', stateCode: 'JH',
      institutions: [
        { name: 'NUSRL Ranchi', type: 'EducationalOrganization', service: 'AI Governance & Law' },
      ],
    },
    {
      state: 'West Bengal', stateCode: 'WB',
      institutions: [
        { name: 'UEM Kolkata', type: 'EducationalOrganization', service: 'AI Governance Workshop' },
      ],
    },
    {
      state: 'Gujarat', stateCode: 'GJ',
      institutions: [
        { name: 'Gujarat National Law University', type: 'EducationalOrganization', service: 'TEDx Talk on AI Governance' },
        { name: 'Dhirubhai Ambani University', type: 'EducationalOrganization', service: 'AI Governance Session' },
      ],
    },
    {
      state: 'Maharashtra', stateCode: 'MH',
      institutions: [
        { name: 'DY Patil University, School of Law', type: 'EducationalOrganization', service: 'Centre for AI & Law Partnership' },
      ],
    },
    {
      state: 'Karnataka', stateCode: 'KA',
      institutions: [
        { name: 'IISc Bengaluru', type: 'EducationalOrganization', service: 'AI Governance Research Engagement' },
        { name: 'Swissnex India, Consulate General of Switzerland, Bengaluru', type: 'GovernmentOrganization', service: 'International AI Governance Dialogue' },
      ],
    },
    {
      state: 'Telangana', stateCode: 'TS',
      institutions: [
        { name: 'ISB Hyderabad', type: 'EducationalOrganization', service: 'Agristack AI Governance Consultation' },
      ],
    },
    {
      state: 'Tamil Nadu', stateCode: 'TN',
      institutions: [
        { name: "AI Legislators' Forum (AILF)", type: 'GovernmentOrganization', service: 'AI Governance Workshop for Legislators' },
      ],
    },
  ];

  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    '@id': `${SITE_URL}/#state-service-areas`,
    name: 'GovernAI — State-wise AI Governance Engagements Across India',
    description:
      'GovernAI delivers AI governance capacity building, ISO/IEC 42001 compliance auditing, and responsible AI policy advisory across 15 Indian states and union territories, engaging 20+ premier institutions.',
    numberOfItems: STATE_ENGAGEMENTS.length,
    itemListElement: STATE_ENGAGEMENTS.map((s, idx) => ({
      '@type': 'ListItem',
      position: idx + 1,
      item: {
        '@type': 'Service',
        '@id': `${SITE_URL}/#service-area-${s.stateCode}`,
        name: `AI Governance Services — ${s.state}`,
        description: `GovernAI's AI governance capacity building, compliance auditing, and policy advisory engagements in ${s.state}, India.`,
        provider: { '@id': `${SITE_URL}/#organization` },
        areaServed: { '@type': 'AdministrativeArea', name: `${s.state}, India` },
        hasOfferCatalog: {
          '@type': 'OfferCatalog',
          name: `AI Governance Engagements in ${s.state}`,
          itemListElement: s.institutions.map((inst) => ({
            '@type': 'Offer',
            itemOffered: {
              '@type': 'Service',
              name: inst.service,
              provider: { '@id': `${SITE_URL}/#organization` },
              serviceOutput: { '@type': 'CreativeWork', name: `${inst.service} at ${inst.name}` },
              areaServed: { '@type': 'AdministrativeArea', name: `${s.state}, India` },
            },
            offeredBy: { '@type': inst.type, name: inst.name },
          })),
        },
      },
    })),
  };
}

/* ── E-E-A-T Trust Backbone Schema ──
   Comprehensive trust signals for Google's ranking:
   - Government endorsements & appointments
   - ISO/IEC certifications & accreditations
   - Institutional partnerships & MOUs
   - Quantitative achievements & impact metrics
   - International affiliations
   - Media & speaking engagements
   This is the SEO "backed by" layer that establishes GovernAI as the
   authoritative entity for AI governance across India. */
export function trustBackboneSchema() {
  return [
    /* ─── 1. Government Endorsements & Official Appointments ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'EndorsementRating',
      '@id': `${SITE_URL}/#govt-endorsements`,
      name: 'Government of India Institutional Endorsements',
      author: { '@id': `${SITE_URL}/#organization` },
      itemReviewed: { '@id': `${SITE_URL}/#organization` },
      reviewBody:
        'GovernAI is endorsed by and operates within premier Government of India institutions including the Indian Institute of Public Administration (IIPA), NIEPA (Ministry of Education), C-DAC (MeitY), and multiple state administrative training institutes.',
    },

    /* ─── 2. Official Government Appointments ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'Role',
      '@id': `${SITE_URL}/#hp-working-group-role`,
      roleName: 'Working Group Member — Digital & AI Governance',
      description:
        'GovernAI Founder Parishrut Jassal appointed as Member of Working Group Committee (I.T. Infrastructure, Cyber-Hubs & Future Ready Industries) for Samridh Himachal-2045, under the Department of Digital Technologies and Governance, Government of Himachal Pradesh.',
      startDate: '2025-07',
      namedPosition: 'Working Group Member',
      memberOf: {
        '@type': 'GovernmentOrganization',
        name: 'Department of Digital Technologies & Governance, Government of Himachal Pradesh',
        parentOrganization: {
          '@type': 'GovernmentOrganization',
          name: 'Government of Himachal Pradesh',
        },
      },
    },

    /* ─── 3. ISO/IEC Certifications & Standards Alignment ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'Certification',
      '@id': `${SITE_URL}/#iso-42001-capability`,
      name: 'ISO/IEC 42001:2023 Compliance & Auditing Capability',
      certificationIdentification: 'ISO/IEC 42001:2023',
      issuedBy: {
        '@type': 'Organization',
        name: 'UKAS (United Kingdom Accreditation Service)',
      },
      about: {
        '@type': 'DefinedTerm',
        name: 'Artificial Intelligence Management System',
        description:
          'International standard specifying requirements for establishing, implementing, maintaining, and continually improving an AI management system within organizations.',
      },
      certificationStatus: 'Active',
      description:
        'GovernAI provides ISO/IEC 42001:2023 compliance gap analysis, readiness reviews, independent AI auditing, and conformity assessments. Founder holds UKAS-recognised ISO/IEC 42001 Lead Auditor certification.',
    },

    /* ─── 4. Institutional Partnerships & MOUs ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      '@id': `${SITE_URL}/#partnerships`,
      name: 'GovernAI Institutional Partnerships & MOUs',
      description:
        'Formal partnerships and memoranda of understanding between GovernAI and leading Indian educational and government institutions.',
      itemListElement: [
        {
          '@type': 'ListItem',
          position: 1,
          item: {
            '@type': 'OrganizationRole',
            name: 'Centre for AI & Law — MOU with DY Patil University',
            description:
              'GovernAI signed an MOU with DY Patil University School of Law to establish a dedicated Centre for AI and Law, advancing responsible AI through interdisciplinary research and policy development.',
            startDate: '2024-10',
            memberOf: {
              '@type': 'EducationalOrganization',
              name: 'DY Patil University, School of Law',
            },
          },
        },
        {
          '@type': 'ListItem',
          position: 2,
          item: {
            '@type': 'OrganizationRole',
            name: 'IndiaAI Data Lab Partnership — C-DAC Mohali',
            description:
              'GovernAI delivers Data Governance, DPDP Act, and Responsible AI training at the IndiaAI Data Lab operated by C-DAC Mohali under MeitY.',
            memberOf: {
              '@type': 'GovernmentOrganization',
              name: 'C-DAC Mohali (Centre for Development of Advanced Computing)',
            },
          },
        },
        {
          '@type': 'ListItem',
          position: 3,
          item: {
            '@type': 'OrganizationRole',
            name: 'IIPA Engagement — Indian Institute of Public Administration',
            description:
              'GovernAI conducts Responsible AI workshops for senior IAS/IPS/IFS officers at the Indian Institute of Public Administration, New Delhi — India\'s premier civil services training institution.',
            memberOf: {
              '@type': 'GovernmentOrganization',
              name: 'Indian Institute of Public Administration (IIPA), New Delhi',
            },
          },
        },
        {
          '@type': 'ListItem',
          position: 4,
          item: {
            '@type': 'OrganizationRole',
            name: 'NIEPA — Ministry of Education Advisory',
            description:
              'GovernAI Founder served as Deputy Advisor at NIEPA (National Institute of Educational Planning and Administration) under the Ministry of Education, Government of India.',
            memberOf: {
              '@type': 'GovernmentOrganization',
              name: 'NIEPA, Ministry of Education, Government of India',
            },
          },
        },
      ],
    },

    /* ─── 5. Quantitative Impact & Achievement Metrics ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': `${SITE_URL}/#impact-metrics`,
      name: 'GovernAI Impact Metrics — AI Governance in India',
      description:
        'Quantitative impact data from GovernAI\'s AI governance engagements across India.',
      creator: { '@id': `${SITE_URL}/#organization` },
      variableMeasured: [
        {
          '@type': 'PropertyValue',
          name: 'Government Officials Trained',
          value: '2000+',
          unitText: 'persons',
          description: 'Senior government officials (IAS, IPS, IFS cadres) trained in AI governance, responsible AI, and compliance frameworks.',
        },
        {
          '@type': 'PropertyValue',
          name: 'Institutional Engagements',
          value: '20+',
          unitText: 'institutions',
          description: 'Premier government bodies, universities, and enterprises engaged across India.',
        },
        {
          '@type': 'PropertyValue',
          name: 'States & Union Territories Covered',
          value: '15',
          unitText: 'states',
          description: 'Indian states and union territories where GovernAI has delivered AI governance services.',
        },
        {
          '@type': 'PropertyValue',
          name: 'Standards Aligned',
          value: 'ISO/IEC 42001, EU AI Act, NIST AI RMF, DPDP Act 2023',
          description: 'International and Indian regulatory frameworks GovernAI aligns with.',
        },
      ],
    },

    /* ─── 6. International Affiliations & Global Credibility ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      '@id': `${SITE_URL}/#international-affiliations`,
      name: 'GovernAI International Affiliations',
      description:
        'Global affiliations and engagements that establish GovernAI\'s international credibility in AI governance.',
      itemListElement: [
        {
          '@type': 'ListItem',
          position: 1,
          item: {
            '@type': 'Organization',
            name: 'ForHumanity (USA)',
            description: 'Independent global body focused on AI audit standards and regulation. GovernAI Founder is a member.',
          },
        },
        {
          '@type': 'ListItem',
          position: 2,
          item: {
            '@type': 'Organization',
            name: 'Center for AI and Digital Policy (Washington, DC)',
            description: 'GovernAI Founder served as AI Policy Research Group Member, contributing to OECD AI Principles and UNESCO AI Ethics analysis.',
          },
        },
        {
          '@type': 'ListItem',
          position: 3,
          item: {
            '@type': 'Organization',
            name: 'Future Shift Labs (FSL)',
            description: 'GovernAI Founder served as Advisor offering Research & Advisory in AI Governance, shaping responsible frameworks aligned with democratic values.',
          },
        },
        {
          '@type': 'ListItem',
          position: 4,
          item: {
            '@type': 'Organization',
            name: 'Swissnex India (Consulate General of Switzerland)',
            description: 'GovernAI engaged in international AI governance dialogue with the Swiss diplomatic mission in Bengaluru.',
          },
        },
        {
          '@type': 'ListItem',
          position: 5,
          item: {
            '@type': 'Organization',
            name: 'ISB Hyderabad',
            description: 'GovernAI contributed to Agristack AI Governance Consultation at the Indian School of Business.',
          },
        },
      ],
    },

    /* ─── 7. Speaking Engagements & Thought Leadership ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      '@id': `${SITE_URL}/#speaking-engagements`,
      name: 'GovernAI Speaking Engagements & Thought Leadership',
      description:
        'TEDx talks, panel discussions, and keynote sessions by GovernAI leadership at premier institutions and conferences.',
      itemListElement: [
        {
          '@type': 'ListItem',
          position: 1,
          item: {
            '@type': 'Event',
            name: 'TEDx GNLU — AI Governance Talk',
            location: { '@type': 'Place', name: 'Gujarat National Law University, Gandhinagar' },
            performer: { '@id': `${SITE_URL}/#founder` },
            eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
          },
        },
        {
          '@type': 'ListItem',
          position: 2,
          item: {
            '@type': 'Event',
            name: 'IndiaAI Impact Summit — Expert Panel',
            location: { '@type': 'Place', name: 'New Delhi, India' },
            performer: { '@id': `${SITE_URL}/#founder` },
          },
        },
        {
          '@type': 'ListItem',
          position: 3,
          item: {
            '@type': 'Event',
            name: 'AAAI 2026 — Panelist on Responsible AI',
            location: { '@type': 'Place', name: 'Association for the Advancement of Artificial Intelligence' },
            performer: { '@id': `${SITE_URL}/#founder` },
          },
        },
        {
          '@type': 'ListItem',
          position: 4,
          item: {
            '@type': 'Event',
            name: 'AI & Healthcare Conference, Mohali',
            performer: { '@type': 'Person', name: 'Dr. Mrudula Bhalke', jobTitle: 'AI & Healthcare Lead' },
          },
        },
        {
          '@type': 'ListItem',
          position: 5,
          item: {
            '@type': 'Event',
            name: 'AI Philanthropy Asia Pacific',
            description: 'GovernAI engagement in AI governance dialogue for the Asia-Pacific region.',
            performer: { '@id': `${SITE_URL}/#founder` },
          },
        },
      ],
    },

    /* ─── 8. Standards & Regulatory Frameworks Expertise ─── */
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      '@id': `${SITE_URL}/#standards-expertise`,
      name: 'GovernAI Regulatory & Standards Expertise',
      description:
        'International and Indian regulatory frameworks in which GovernAI provides compliance advisory, auditing, and implementation support.',
      itemListElement: [
        { '@type': 'ListItem', position: 1, item: { '@type': 'DefinedTerm', name: 'ISO/IEC 42001:2023', description: 'AI Management System — international standard for responsible AI governance.' } },
        { '@type': 'ListItem', position: 2, item: { '@type': 'DefinedTerm', name: 'EU AI Act', description: 'European Union regulation on artificial intelligence risk classification and compliance.' } },
        { '@type': 'ListItem', position: 3, item: { '@type': 'DefinedTerm', name: 'NIST AI Risk Management Framework (AI RMF)', description: 'US National Institute of Standards and Technology framework for managing AI risks.' } },
        { '@type': 'ListItem', position: 4, item: { '@type': 'DefinedTerm', name: 'Digital Personal Data Protection Act 2023 (DPDP Act)', description: 'India\'s data protection legislation governing personal data processing and AI.' } },
        { '@type': 'ListItem', position: 5, item: { '@type': 'DefinedTerm', name: 'DPDP Rules 2025', description: 'Implementation rules under the DPDP Act specifying compliance requirements for AI systems.' } },
        { '@type': 'ListItem', position: 6, item: { '@type': 'DefinedTerm', name: 'OECD AI Principles', description: 'OECD guidelines for trustworthy AI adopted by 46 countries.' } },
        { '@type': 'ListItem', position: 7, item: { '@type': 'DefinedTerm', name: 'UNESCO Recommendation on the Ethics of AI', description: 'Global normative instrument on AI ethics adopted by 193 member states.' } },
      ],
    },
  ];
}
